linters-settings:
  dupl:
    threshold: 100
  errorlint:
    errorf: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
  funlen:
    lines: 65
    statements: 40
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 10
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - unnecessaryBlock
  gofumpt:
    extra-rules: true
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nestif:
    min-complexity: 4
  nolintlint:
    require-explanation: true
    require-specific: true
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/MatthewBehnke/apis) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
    # Skip generated files.
    # Default: true
    skip-generated: true


# The committed out linters all currently do not pass. There should be some effort to 
# enable more of the linters sometime soon but go ahead and see if you can fix any of 
# them.  
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    # - cyclop
    # - depguard
    - dogsled
    - dupl
    - durationcheck
    # - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gci
    # - gochecknoglobals
    - gochecknoinits
    # - gocognit
    - goconst
    # - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - goerr113
    - gofmt
    # - gofumpt
    - goimports
    # - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    # - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    # - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    # - revive // easy fixes
    - staticcheck
    # - stylecheck # easy fixes
    - tparallel
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

# issues:
  # exclude-rules:
  #   - path: integration-test
  #     linters:
  #       - paralleltest
  #       - godot
    # - path: internal/controller/http
    #   linters:
    #     - godot

run:
  skip-dirs:
    - docs
    - testing
