// Code generated by ent, DO NOT EDIT.

package itembatchtoitembatch

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"

	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldLTE(FieldID, id))
}

// ChildUUID applies equality check predicate on the "childUUID" field. It's identical to ChildUUIDEQ.
func ChildUUID(v uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldEQ(FieldChildUUID, v))
}

// ParentUUID applies equality check predicate on the "parentUUID" field. It's identical to ParentUUIDEQ.
func ParentUUID(v uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldEQ(FieldParentUUID, v))
}

// ChildUUIDEQ applies the EQ predicate on the "childUUID" field.
func ChildUUIDEQ(v uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldEQ(FieldChildUUID, v))
}

// ChildUUIDNEQ applies the NEQ predicate on the "childUUID" field.
func ChildUUIDNEQ(v uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldNEQ(FieldChildUUID, v))
}

// ChildUUIDIn applies the In predicate on the "childUUID" field.
func ChildUUIDIn(vs ...uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldIn(FieldChildUUID, vs...))
}

// ChildUUIDNotIn applies the NotIn predicate on the "childUUID" field.
func ChildUUIDNotIn(vs ...uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldNotIn(FieldChildUUID, vs...))
}

// ParentUUIDEQ applies the EQ predicate on the "parentUUID" field.
func ParentUUIDEQ(v uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldEQ(FieldParentUUID, v))
}

// ParentUUIDNEQ applies the NEQ predicate on the "parentUUID" field.
func ParentUUIDNEQ(v uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldNEQ(FieldParentUUID, v))
}

// ParentUUIDIn applies the In predicate on the "parentUUID" field.
func ParentUUIDIn(vs ...uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldIn(FieldParentUUID, vs...))
}

// ParentUUIDNotIn applies the NotIn predicate on the "parentUUID" field.
func ParentUUIDNotIn(vs ...uuid.UUID) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(sql.FieldNotIn(FieldParentUUID, vs...))
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.ItemBatch) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ParentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChild applies the HasEdge predicate on the "child" edge.
func HasChild() predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ChildTable, ChildColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildWith applies the HasEdge predicate on the "child" edge with a given conditions (other predicates).
func HasChildWith(preds ...predicate.ItemBatch) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ChildInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ChildTable, ChildColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ItemBatchToItemBatch) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ItemBatchToItemBatch) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ItemBatchToItemBatch) predicate.ItemBatchToItemBatch {
	return predicate.ItemBatchToItemBatch(func(s *sql.Selector) {
		p(s.Not())
	})
}
