// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/attributetype"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/company"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/predicate"
)

// AttributeTypeQuery is the builder for querying AttributeType entities.
type AttributeTypeQuery struct {
	config
	ctx         *QueryContext
	order       []OrderFunc
	inters      []Interceptor
	predicates  []predicate.AttributeType
	withCompany *CompanyQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AttributeTypeQuery builder.
func (atq *AttributeTypeQuery) Where(ps ...predicate.AttributeType) *AttributeTypeQuery {
	atq.predicates = append(atq.predicates, ps...)
	return atq
}

// Limit the number of records to be returned by this query.
func (atq *AttributeTypeQuery) Limit(limit int) *AttributeTypeQuery {
	atq.ctx.Limit = &limit
	return atq
}

// Offset to start from.
func (atq *AttributeTypeQuery) Offset(offset int) *AttributeTypeQuery {
	atq.ctx.Offset = &offset
	return atq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (atq *AttributeTypeQuery) Unique(unique bool) *AttributeTypeQuery {
	atq.ctx.Unique = &unique
	return atq
}

// Order specifies how the records should be ordered.
func (atq *AttributeTypeQuery) Order(o ...OrderFunc) *AttributeTypeQuery {
	atq.order = append(atq.order, o...)
	return atq
}

// QueryCompany chains the current query on the "company" edge.
func (atq *AttributeTypeQuery) QueryCompany() *CompanyQuery {
	query := (&CompanyClient{config: atq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := atq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := atq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(attributetype.Table, attributetype.FieldID, selector),
			sqlgraph.To(company.Table, company.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, attributetype.CompanyTable, attributetype.CompanyColumn),
		)
		fromU = sqlgraph.SetNeighbors(atq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AttributeType entity from the query.
// Returns a *NotFoundError when no AttributeType was found.
func (atq *AttributeTypeQuery) First(ctx context.Context) (*AttributeType, error) {
	nodes, err := atq.Limit(1).All(setContextOp(ctx, atq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{attributetype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (atq *AttributeTypeQuery) FirstX(ctx context.Context) *AttributeType {
	node, err := atq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AttributeType ID from the query.
// Returns a *NotFoundError when no AttributeType ID was found.
func (atq *AttributeTypeQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = atq.Limit(1).IDs(setContextOp(ctx, atq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{attributetype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (atq *AttributeTypeQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := atq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AttributeType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AttributeType entity is found.
// Returns a *NotFoundError when no AttributeType entities are found.
func (atq *AttributeTypeQuery) Only(ctx context.Context) (*AttributeType, error) {
	nodes, err := atq.Limit(2).All(setContextOp(ctx, atq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{attributetype.Label}
	default:
		return nil, &NotSingularError{attributetype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (atq *AttributeTypeQuery) OnlyX(ctx context.Context) *AttributeType {
	node, err := atq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AttributeType ID in the query.
// Returns a *NotSingularError when more than one AttributeType ID is found.
// Returns a *NotFoundError when no entities are found.
func (atq *AttributeTypeQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = atq.Limit(2).IDs(setContextOp(ctx, atq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{attributetype.Label}
	default:
		err = &NotSingularError{attributetype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (atq *AttributeTypeQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := atq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AttributeTypes.
func (atq *AttributeTypeQuery) All(ctx context.Context) ([]*AttributeType, error) {
	ctx = setContextOp(ctx, atq.ctx, "All")
	if err := atq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AttributeType, *AttributeTypeQuery]()
	return withInterceptors[[]*AttributeType](ctx, atq, qr, atq.inters)
}

// AllX is like All, but panics if an error occurs.
func (atq *AttributeTypeQuery) AllX(ctx context.Context) []*AttributeType {
	nodes, err := atq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AttributeType IDs.
func (atq *AttributeTypeQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if atq.ctx.Unique == nil && atq.path != nil {
		atq.Unique(true)
	}
	ctx = setContextOp(ctx, atq.ctx, "IDs")
	if err = atq.Select(attributetype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (atq *AttributeTypeQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := atq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (atq *AttributeTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, atq.ctx, "Count")
	if err := atq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, atq, querierCount[*AttributeTypeQuery](), atq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (atq *AttributeTypeQuery) CountX(ctx context.Context) int {
	count, err := atq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (atq *AttributeTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, atq.ctx, "Exist")
	switch _, err := atq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (atq *AttributeTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := atq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AttributeTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (atq *AttributeTypeQuery) Clone() *AttributeTypeQuery {
	if atq == nil {
		return nil
	}
	return &AttributeTypeQuery{
		config:      atq.config,
		ctx:         atq.ctx.Clone(),
		order:       append([]OrderFunc{}, atq.order...),
		inters:      append([]Interceptor{}, atq.inters...),
		predicates:  append([]predicate.AttributeType{}, atq.predicates...),
		withCompany: atq.withCompany.Clone(),
		// clone intermediate query.
		sql:  atq.sql.Clone(),
		path: atq.path,
	}
}

// WithCompany tells the query-builder to eager-load the nodes that are connected to
// the "company" edge. The optional arguments are used to configure the query builder of the edge.
func (atq *AttributeTypeQuery) WithCompany(opts ...func(*CompanyQuery)) *AttributeTypeQuery {
	query := (&CompanyClient{config: atq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	atq.withCompany = query
	return atq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	httpclient.AttributeType.Query().
//		GroupBy(attributetype.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (atq *AttributeTypeQuery) GroupBy(field string, fields ...string) *AttributeTypeGroupBy {
	atq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AttributeTypeGroupBy{build: atq}
	grbuild.flds = &atq.ctx.Fields
	grbuild.label = attributetype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	httpclient.AttributeType.Query().
//		Select(attributetype.FieldKey).
//		Scan(ctx, &v)
func (atq *AttributeTypeQuery) Select(fields ...string) *AttributeTypeSelect {
	atq.ctx.Fields = append(atq.ctx.Fields, fields...)
	sbuild := &AttributeTypeSelect{AttributeTypeQuery: atq}
	sbuild.label = attributetype.Label
	sbuild.flds, sbuild.scan = &atq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AttributeTypeSelect configured with the given aggregations.
func (atq *AttributeTypeQuery) Aggregate(fns ...AggregateFunc) *AttributeTypeSelect {
	return atq.Select().Aggregate(fns...)
}

func (atq *AttributeTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range atq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, atq); err != nil {
				return err
			}
		}
	}
	for _, f := range atq.ctx.Fields {
		if !attributetype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if atq.path != nil {
		prev, err := atq.path(ctx)
		if err != nil {
			return err
		}
		atq.sql = prev
	}
	return nil
}

func (atq *AttributeTypeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AttributeType, error) {
	var (
		nodes       = []*AttributeType{}
		_spec       = atq.querySpec()
		loadedTypes = [1]bool{
			atq.withCompany != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AttributeType).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AttributeType{config: atq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(atq.modifiers) > 0 {
		_spec.Modifiers = atq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, atq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := atq.withCompany; query != nil {
		if err := atq.loadCompany(ctx, query, nodes, nil,
			func(n *AttributeType, e *Company) { n.Edges.Company = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (atq *AttributeTypeQuery) loadCompany(ctx context.Context, query *CompanyQuery, nodes []*AttributeType, init func(*AttributeType), assign func(*AttributeType, *Company)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AttributeType)
	for i := range nodes {
		fk := nodes[i].CompanyUUID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(company.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "companyUUID" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (atq *AttributeTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := atq.querySpec()
	if len(atq.modifiers) > 0 {
		_spec.Modifiers = atq.modifiers
	}
	_spec.Node.Columns = atq.ctx.Fields
	if len(atq.ctx.Fields) > 0 {
		_spec.Unique = atq.ctx.Unique != nil && *atq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, atq.driver, _spec)
}

func (atq *AttributeTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(attributetype.Table, attributetype.Columns, sqlgraph.NewFieldSpec(attributetype.FieldID, field.TypeUUID))
	_spec.From = atq.sql
	if unique := atq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if atq.path != nil {
		_spec.Unique = true
	}
	if fields := atq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attributetype.FieldID)
		for i := range fields {
			if fields[i] != attributetype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := atq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := atq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := atq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := atq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (atq *AttributeTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(atq.driver.Dialect())
	t1 := builder.Table(attributetype.Table)
	columns := atq.ctx.Fields
	if len(columns) == 0 {
		columns = attributetype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if atq.sql != nil {
		selector = atq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if atq.ctx.Unique != nil && *atq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range atq.modifiers {
		m(selector)
	}
	for _, p := range atq.predicates {
		p(selector)
	}
	for _, p := range atq.order {
		p(selector)
	}
	if offset := atq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := atq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (atq *AttributeTypeQuery) ForUpdate(opts ...sql.LockOption) *AttributeTypeQuery {
	if atq.driver.Dialect() == dialect.Postgres {
		atq.Unique(false)
	}
	atq.modifiers = append(atq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return atq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (atq *AttributeTypeQuery) ForShare(opts ...sql.LockOption) *AttributeTypeQuery {
	if atq.driver.Dialect() == dialect.Postgres {
		atq.Unique(false)
	}
	atq.modifiers = append(atq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return atq
}

// AttributeTypeGroupBy is the group-by builder for AttributeType entities.
type AttributeTypeGroupBy struct {
	selector
	build *AttributeTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (atgb *AttributeTypeGroupBy) Aggregate(fns ...AggregateFunc) *AttributeTypeGroupBy {
	atgb.fns = append(atgb.fns, fns...)
	return atgb
}

// Scan applies the selector query and scans the result into the given value.
func (atgb *AttributeTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, atgb.build.ctx, "GroupBy")
	if err := atgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AttributeTypeQuery, *AttributeTypeGroupBy](ctx, atgb.build, atgb, atgb.build.inters, v)
}

func (atgb *AttributeTypeGroupBy) sqlScan(ctx context.Context, root *AttributeTypeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(atgb.fns))
	for _, fn := range atgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*atgb.flds)+len(atgb.fns))
		for _, f := range *atgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*atgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := atgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AttributeTypeSelect is the builder for selecting fields of AttributeType entities.
type AttributeTypeSelect struct {
	*AttributeTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ats *AttributeTypeSelect) Aggregate(fns ...AggregateFunc) *AttributeTypeSelect {
	ats.fns = append(ats.fns, fns...)
	return ats
}

// Scan applies the selector query and scans the result into the given value.
func (ats *AttributeTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ats.ctx, "Select")
	if err := ats.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AttributeTypeQuery, *AttributeTypeSelect](ctx, ats.AttributeTypeQuery, ats, ats.inters, v)
}

func (ats *AttributeTypeSelect) sqlScan(ctx context.Context, root *AttributeTypeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ats.fns))
	for _, fn := range ats.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ats.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ats.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
