// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/attributetype"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/company"
)

// AttributeTypeCreate is the builder for creating a AttributeType entity.
type AttributeTypeCreate struct {
	config
	mutation *AttributeTypeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (atc *AttributeTypeCreate) SetKey(s string) *AttributeTypeCreate {
	atc.mutation.SetKey(s)
	return atc
}

// SetCompanyUUID sets the "companyUUID" field.
func (atc *AttributeTypeCreate) SetCompanyUUID(u uuid.UUID) *AttributeTypeCreate {
	atc.mutation.SetCompanyUUID(u)
	return atc
}

// SetID sets the "id" field.
func (atc *AttributeTypeCreate) SetID(u uuid.UUID) *AttributeTypeCreate {
	atc.mutation.SetID(u)
	return atc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (atc *AttributeTypeCreate) SetNillableID(u *uuid.UUID) *AttributeTypeCreate {
	if u != nil {
		atc.SetID(*u)
	}
	return atc
}

// SetCompanyID sets the "company" edge to the Company entity by ID.
func (atc *AttributeTypeCreate) SetCompanyID(id uuid.UUID) *AttributeTypeCreate {
	atc.mutation.SetCompanyID(id)
	return atc
}

// SetCompany sets the "company" edge to the Company entity.
func (atc *AttributeTypeCreate) SetCompany(c *Company) *AttributeTypeCreate {
	return atc.SetCompanyID(c.ID)
}

// Mutation returns the AttributeTypeMutation object of the builder.
func (atc *AttributeTypeCreate) Mutation() *AttributeTypeMutation {
	return atc.mutation
}

// Save creates the AttributeType in the database.
func (atc *AttributeTypeCreate) Save(ctx context.Context) (*AttributeType, error) {
	atc.defaults()
	return withHooks[*AttributeType, AttributeTypeMutation](ctx, atc.sqlSave, atc.mutation, atc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (atc *AttributeTypeCreate) SaveX(ctx context.Context) *AttributeType {
	v, err := atc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atc *AttributeTypeCreate) Exec(ctx context.Context) error {
	_, err := atc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atc *AttributeTypeCreate) ExecX(ctx context.Context) {
	if err := atc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (atc *AttributeTypeCreate) defaults() {
	if _, ok := atc.mutation.ID(); !ok {
		v := attributetype.DefaultID()
		atc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atc *AttributeTypeCreate) check() error {
	if _, ok := atc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "AttributeType.key"`)}
	}
	if _, ok := atc.mutation.CompanyUUID(); !ok {
		return &ValidationError{Name: "companyUUID", err: errors.New(`ent: missing required field "AttributeType.companyUUID"`)}
	}
	if _, ok := atc.mutation.CompanyID(); !ok {
		return &ValidationError{Name: "company", err: errors.New(`ent: missing required edge "AttributeType.company"`)}
	}
	return nil
}

func (atc *AttributeTypeCreate) sqlSave(ctx context.Context) (*AttributeType, error) {
	if err := atc.check(); err != nil {
		return nil, err
	}
	_node, _spec := atc.createSpec()
	if err := sqlgraph.CreateNode(ctx, atc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	atc.mutation.id = &_node.ID
	atc.mutation.done = true
	return _node, nil
}

func (atc *AttributeTypeCreate) createSpec() (*AttributeType, *sqlgraph.CreateSpec) {
	var (
		_node = &AttributeType{config: atc.config}
		_spec = sqlgraph.NewCreateSpec(attributetype.Table, sqlgraph.NewFieldSpec(attributetype.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = atc.conflict
	if id, ok := atc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := atc.mutation.Key(); ok {
		_spec.SetField(attributetype.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if nodes := atc.mutation.CompanyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attributetype.CompanyTable,
			Columns: []string{attributetype.CompanyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CompanyUUID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AttributeType.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AttributeTypeUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (atc *AttributeTypeCreate) OnConflict(opts ...sql.ConflictOption) *AttributeTypeUpsertOne {
	atc.conflict = opts
	return &AttributeTypeUpsertOne{
		create: atc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AttributeType.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (atc *AttributeTypeCreate) OnConflictColumns(columns ...string) *AttributeTypeUpsertOne {
	atc.conflict = append(atc.conflict, sql.ConflictColumns(columns...))
	return &AttributeTypeUpsertOne{
		create: atc,
	}
}

type (
	// AttributeTypeUpsertOne is the builder for "upsert"-ing
	//  one AttributeType node.
	AttributeTypeUpsertOne struct {
		create *AttributeTypeCreate
	}

	// AttributeTypeUpsert is the "OnConflict" setter.
	AttributeTypeUpsert struct {
		*sql.UpdateSet
	}
)

// SetKey sets the "key" field.
func (u *AttributeTypeUpsert) SetKey(v string) *AttributeTypeUpsert {
	u.Set(attributetype.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *AttributeTypeUpsert) UpdateKey() *AttributeTypeUpsert {
	u.SetExcluded(attributetype.FieldKey)
	return u
}

// SetCompanyUUID sets the "companyUUID" field.
func (u *AttributeTypeUpsert) SetCompanyUUID(v uuid.UUID) *AttributeTypeUpsert {
	u.Set(attributetype.FieldCompanyUUID, v)
	return u
}

// UpdateCompanyUUID sets the "companyUUID" field to the value that was provided on create.
func (u *AttributeTypeUpsert) UpdateCompanyUUID() *AttributeTypeUpsert {
	u.SetExcluded(attributetype.FieldCompanyUUID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AttributeType.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(attributetype.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AttributeTypeUpsertOne) UpdateNewValues() *AttributeTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(attributetype.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AttributeType.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AttributeTypeUpsertOne) Ignore() *AttributeTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AttributeTypeUpsertOne) DoNothing() *AttributeTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AttributeTypeCreate.OnConflict
// documentation for more info.
func (u *AttributeTypeUpsertOne) Update(set func(*AttributeTypeUpsert)) *AttributeTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AttributeTypeUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *AttributeTypeUpsertOne) SetKey(v string) *AttributeTypeUpsertOne {
	return u.Update(func(s *AttributeTypeUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *AttributeTypeUpsertOne) UpdateKey() *AttributeTypeUpsertOne {
	return u.Update(func(s *AttributeTypeUpsert) {
		s.UpdateKey()
	})
}

// SetCompanyUUID sets the "companyUUID" field.
func (u *AttributeTypeUpsertOne) SetCompanyUUID(v uuid.UUID) *AttributeTypeUpsertOne {
	return u.Update(func(s *AttributeTypeUpsert) {
		s.SetCompanyUUID(v)
	})
}

// UpdateCompanyUUID sets the "companyUUID" field to the value that was provided on create.
func (u *AttributeTypeUpsertOne) UpdateCompanyUUID() *AttributeTypeUpsertOne {
	return u.Update(func(s *AttributeTypeUpsert) {
		s.UpdateCompanyUUID()
	})
}

// Exec executes the query.
func (u *AttributeTypeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AttributeTypeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AttributeTypeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AttributeTypeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AttributeTypeUpsertOne.ID is not supported by MySQL driver. Use AttributeTypeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AttributeTypeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AttributeTypeCreateBulk is the builder for creating many AttributeType entities in bulk.
type AttributeTypeCreateBulk struct {
	config
	builders []*AttributeTypeCreate
	conflict []sql.ConflictOption
}

// Save creates the AttributeType entities in the database.
func (atcb *AttributeTypeCreateBulk) Save(ctx context.Context) ([]*AttributeType, error) {
	specs := make([]*sqlgraph.CreateSpec, len(atcb.builders))
	nodes := make([]*AttributeType, len(atcb.builders))
	mutators := make([]Mutator, len(atcb.builders))
	for i := range atcb.builders {
		func(i int, root context.Context) {
			builder := atcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttributeTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, atcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = atcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, atcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, atcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (atcb *AttributeTypeCreateBulk) SaveX(ctx context.Context) []*AttributeType {
	v, err := atcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atcb *AttributeTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := atcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atcb *AttributeTypeCreateBulk) ExecX(ctx context.Context) {
	if err := atcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AttributeType.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AttributeTypeUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (atcb *AttributeTypeCreateBulk) OnConflict(opts ...sql.ConflictOption) *AttributeTypeUpsertBulk {
	atcb.conflict = opts
	return &AttributeTypeUpsertBulk{
		create: atcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AttributeType.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (atcb *AttributeTypeCreateBulk) OnConflictColumns(columns ...string) *AttributeTypeUpsertBulk {
	atcb.conflict = append(atcb.conflict, sql.ConflictColumns(columns...))
	return &AttributeTypeUpsertBulk{
		create: atcb,
	}
}

// AttributeTypeUpsertBulk is the builder for "upsert"-ing
// a bulk of AttributeType nodes.
type AttributeTypeUpsertBulk struct {
	create *AttributeTypeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AttributeType.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(attributetype.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AttributeTypeUpsertBulk) UpdateNewValues() *AttributeTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(attributetype.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AttributeType.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AttributeTypeUpsertBulk) Ignore() *AttributeTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AttributeTypeUpsertBulk) DoNothing() *AttributeTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AttributeTypeCreateBulk.OnConflict
// documentation for more info.
func (u *AttributeTypeUpsertBulk) Update(set func(*AttributeTypeUpsert)) *AttributeTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AttributeTypeUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *AttributeTypeUpsertBulk) SetKey(v string) *AttributeTypeUpsertBulk {
	return u.Update(func(s *AttributeTypeUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *AttributeTypeUpsertBulk) UpdateKey() *AttributeTypeUpsertBulk {
	return u.Update(func(s *AttributeTypeUpsert) {
		s.UpdateKey()
	})
}

// SetCompanyUUID sets the "companyUUID" field.
func (u *AttributeTypeUpsertBulk) SetCompanyUUID(v uuid.UUID) *AttributeTypeUpsertBulk {
	return u.Update(func(s *AttributeTypeUpsert) {
		s.SetCompanyUUID(v)
	})
}

// UpdateCompanyUUID sets the "companyUUID" field to the value that was provided on create.
func (u *AttributeTypeUpsertBulk) UpdateCompanyUUID() *AttributeTypeUpsertBulk {
	return u.Update(func(s *AttributeTypeUpsert) {
		s.UpdateCompanyUUID()
	})
}

// Exec executes the query.
func (u *AttributeTypeUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AttributeTypeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AttributeTypeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AttributeTypeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
