// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"github.com/MatthewBehnke/apis/pkg/database/ent/authorizationpolicy"
	"github.com/MatthewBehnke/apis/pkg/database/ent/predicate"
)

// AuthorizationPolicyDelete is the builder for deleting a AuthorizationPolicy entity.
type AuthorizationPolicyDelete struct {
	config
	hooks    []Hook
	mutation *AuthorizationPolicyMutation
}

// Where appends a list predicates to the AuthorizationPolicyDelete builder.
func (apd *AuthorizationPolicyDelete) Where(ps ...predicate.AuthorizationPolicy) *AuthorizationPolicyDelete {
	apd.mutation.Where(ps...)
	return apd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (apd *AuthorizationPolicyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(apd.hooks) == 0 {
		affected, err = apd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthorizationPolicyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			apd.mutation = mutation
			affected, err = apd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(apd.hooks) - 1; i >= 0; i-- {
			if apd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = apd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, apd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (apd *AuthorizationPolicyDelete) ExecX(ctx context.Context) int {
	n, err := apd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (apd *AuthorizationPolicyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: authorizationpolicy.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: authorizationpolicy.FieldID,
			},
		},
	}
	if ps := apd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, apd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// AuthorizationPolicyDeleteOne is the builder for deleting a single AuthorizationPolicy entity.
type AuthorizationPolicyDeleteOne struct {
	apd *AuthorizationPolicyDelete
}

// Exec executes the deletion query.
func (apdo *AuthorizationPolicyDeleteOne) Exec(ctx context.Context) error {
	n, err := apdo.apd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authorizationpolicy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (apdo *AuthorizationPolicyDeleteOne) ExecX(ctx context.Context) {
	apdo.apd.ExecX(ctx)
}
