// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/certificationhistory"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/enthistory"
)

// CertificationHistoryCreate is the builder for creating a CertificationHistory entity.
type CertificationHistoryCreate struct {
	config
	mutation *CertificationHistoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetHistoryTime sets the "history_time" field.
func (chc *CertificationHistoryCreate) SetHistoryTime(t time.Time) *CertificationHistoryCreate {
	chc.mutation.SetHistoryTime(t)
	return chc
}

// SetNillableHistoryTime sets the "history_time" field if the given value is not nil.
func (chc *CertificationHistoryCreate) SetNillableHistoryTime(t *time.Time) *CertificationHistoryCreate {
	if t != nil {
		chc.SetHistoryTime(*t)
	}
	return chc
}

// SetRef sets the "ref" field.
func (chc *CertificationHistoryCreate) SetRef(u uuid.UUID) *CertificationHistoryCreate {
	chc.mutation.SetRef(u)
	return chc
}

// SetNillableRef sets the "ref" field if the given value is not nil.
func (chc *CertificationHistoryCreate) SetNillableRef(u *uuid.UUID) *CertificationHistoryCreate {
	if u != nil {
		chc.SetRef(*u)
	}
	return chc
}

// SetOperation sets the "operation" field.
func (chc *CertificationHistoryCreate) SetOperation(et enthistory.OpType) *CertificationHistoryCreate {
	chc.mutation.SetOperation(et)
	return chc
}

// SetUpdatedBy sets the "updated_by" field.
func (chc *CertificationHistoryCreate) SetUpdatedBy(s string) *CertificationHistoryCreate {
	chc.mutation.SetUpdatedBy(s)
	return chc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (chc *CertificationHistoryCreate) SetNillableUpdatedBy(s *string) *CertificationHistoryCreate {
	if s != nil {
		chc.SetUpdatedBy(*s)
	}
	return chc
}

// SetPrimaryAttribute sets the "primaryAttribute" field.
func (chc *CertificationHistoryCreate) SetPrimaryAttribute(s string) *CertificationHistoryCreate {
	chc.mutation.SetPrimaryAttribute(s)
	return chc
}

// SetCompanyUUID sets the "companyUUID" field.
func (chc *CertificationHistoryCreate) SetCompanyUUID(u uuid.UUID) *CertificationHistoryCreate {
	chc.mutation.SetCompanyUUID(u)
	return chc
}

// SetItemBatchUUID sets the "itemBatchUUID" field.
func (chc *CertificationHistoryCreate) SetItemBatchUUID(u uuid.UUID) *CertificationHistoryCreate {
	chc.mutation.SetItemBatchUUID(u)
	return chc
}

// SetImageUUID sets the "imageUUID" field.
func (chc *CertificationHistoryCreate) SetImageUUID(u uuid.UUID) *CertificationHistoryCreate {
	chc.mutation.SetImageUUID(u)
	return chc
}

// SetID sets the "id" field.
func (chc *CertificationHistoryCreate) SetID(u uuid.UUID) *CertificationHistoryCreate {
	chc.mutation.SetID(u)
	return chc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (chc *CertificationHistoryCreate) SetNillableID(u *uuid.UUID) *CertificationHistoryCreate {
	if u != nil {
		chc.SetID(*u)
	}
	return chc
}

// Mutation returns the CertificationHistoryMutation object of the builder.
func (chc *CertificationHistoryCreate) Mutation() *CertificationHistoryMutation {
	return chc.mutation
}

// Save creates the CertificationHistory in the database.
func (chc *CertificationHistoryCreate) Save(ctx context.Context) (*CertificationHistory, error) {
	chc.defaults()
	return withHooks[*CertificationHistory, CertificationHistoryMutation](ctx, chc.sqlSave, chc.mutation, chc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (chc *CertificationHistoryCreate) SaveX(ctx context.Context) *CertificationHistory {
	v, err := chc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (chc *CertificationHistoryCreate) Exec(ctx context.Context) error {
	_, err := chc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (chc *CertificationHistoryCreate) ExecX(ctx context.Context) {
	if err := chc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (chc *CertificationHistoryCreate) defaults() {
	if _, ok := chc.mutation.HistoryTime(); !ok {
		v := certificationhistory.DefaultHistoryTime()
		chc.mutation.SetHistoryTime(v)
	}
	if _, ok := chc.mutation.ID(); !ok {
		v := certificationhistory.DefaultID()
		chc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (chc *CertificationHistoryCreate) check() error {
	if _, ok := chc.mutation.HistoryTime(); !ok {
		return &ValidationError{Name: "history_time", err: errors.New(`ent: missing required field "CertificationHistory.history_time"`)}
	}
	if _, ok := chc.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "CertificationHistory.operation"`)}
	}
	if v, ok := chc.mutation.Operation(); ok {
		if err := certificationhistory.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "CertificationHistory.operation": %w`, err)}
		}
	}
	if _, ok := chc.mutation.PrimaryAttribute(); !ok {
		return &ValidationError{Name: "primaryAttribute", err: errors.New(`ent: missing required field "CertificationHistory.primaryAttribute"`)}
	}
	if _, ok := chc.mutation.CompanyUUID(); !ok {
		return &ValidationError{Name: "companyUUID", err: errors.New(`ent: missing required field "CertificationHistory.companyUUID"`)}
	}
	if _, ok := chc.mutation.ItemBatchUUID(); !ok {
		return &ValidationError{Name: "itemBatchUUID", err: errors.New(`ent: missing required field "CertificationHistory.itemBatchUUID"`)}
	}
	if _, ok := chc.mutation.ImageUUID(); !ok {
		return &ValidationError{Name: "imageUUID", err: errors.New(`ent: missing required field "CertificationHistory.imageUUID"`)}
	}
	return nil
}

func (chc *CertificationHistoryCreate) sqlSave(ctx context.Context) (*CertificationHistory, error) {
	if err := chc.check(); err != nil {
		return nil, err
	}
	_node, _spec := chc.createSpec()
	if err := sqlgraph.CreateNode(ctx, chc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	chc.mutation.id = &_node.ID
	chc.mutation.done = true
	return _node, nil
}

func (chc *CertificationHistoryCreate) createSpec() (*CertificationHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &CertificationHistory{config: chc.config}
		_spec = sqlgraph.NewCreateSpec(certificationhistory.Table, sqlgraph.NewFieldSpec(certificationhistory.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = chc.conflict
	if id, ok := chc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := chc.mutation.HistoryTime(); ok {
		_spec.SetField(certificationhistory.FieldHistoryTime, field.TypeTime, value)
		_node.HistoryTime = value
	}
	if value, ok := chc.mutation.Ref(); ok {
		_spec.SetField(certificationhistory.FieldRef, field.TypeUUID, value)
		_node.Ref = value
	}
	if value, ok := chc.mutation.Operation(); ok {
		_spec.SetField(certificationhistory.FieldOperation, field.TypeEnum, value)
		_node.Operation = value
	}
	if value, ok := chc.mutation.UpdatedBy(); ok {
		_spec.SetField(certificationhistory.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = &value
	}
	if value, ok := chc.mutation.PrimaryAttribute(); ok {
		_spec.SetField(certificationhistory.FieldPrimaryAttribute, field.TypeString, value)
		_node.PrimaryAttribute = value
	}
	if value, ok := chc.mutation.CompanyUUID(); ok {
		_spec.SetField(certificationhistory.FieldCompanyUUID, field.TypeUUID, value)
		_node.CompanyUUID = value
	}
	if value, ok := chc.mutation.ItemBatchUUID(); ok {
		_spec.SetField(certificationhistory.FieldItemBatchUUID, field.TypeUUID, value)
		_node.ItemBatchUUID = value
	}
	if value, ok := chc.mutation.ImageUUID(); ok {
		_spec.SetField(certificationhistory.FieldImageUUID, field.TypeUUID, value)
		_node.ImageUUID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CertificationHistory.Create().
//		SetHistoryTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CertificationHistoryUpsert) {
//			SetHistoryTime(v+v).
//		}).
//		Exec(ctx)
func (chc *CertificationHistoryCreate) OnConflict(opts ...sql.ConflictOption) *CertificationHistoryUpsertOne {
	chc.conflict = opts
	return &CertificationHistoryUpsertOne{
		create: chc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CertificationHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (chc *CertificationHistoryCreate) OnConflictColumns(columns ...string) *CertificationHistoryUpsertOne {
	chc.conflict = append(chc.conflict, sql.ConflictColumns(columns...))
	return &CertificationHistoryUpsertOne{
		create: chc,
	}
}

type (
	// CertificationHistoryUpsertOne is the builder for "upsert"-ing
	//  one CertificationHistory node.
	CertificationHistoryUpsertOne struct {
		create *CertificationHistoryCreate
	}

	// CertificationHistoryUpsert is the "OnConflict" setter.
	CertificationHistoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetPrimaryAttribute sets the "primaryAttribute" field.
func (u *CertificationHistoryUpsert) SetPrimaryAttribute(v string) *CertificationHistoryUpsert {
	u.Set(certificationhistory.FieldPrimaryAttribute, v)
	return u
}

// UpdatePrimaryAttribute sets the "primaryAttribute" field to the value that was provided on create.
func (u *CertificationHistoryUpsert) UpdatePrimaryAttribute() *CertificationHistoryUpsert {
	u.SetExcluded(certificationhistory.FieldPrimaryAttribute)
	return u
}

// SetCompanyUUID sets the "companyUUID" field.
func (u *CertificationHistoryUpsert) SetCompanyUUID(v uuid.UUID) *CertificationHistoryUpsert {
	u.Set(certificationhistory.FieldCompanyUUID, v)
	return u
}

// UpdateCompanyUUID sets the "companyUUID" field to the value that was provided on create.
func (u *CertificationHistoryUpsert) UpdateCompanyUUID() *CertificationHistoryUpsert {
	u.SetExcluded(certificationhistory.FieldCompanyUUID)
	return u
}

// SetItemBatchUUID sets the "itemBatchUUID" field.
func (u *CertificationHistoryUpsert) SetItemBatchUUID(v uuid.UUID) *CertificationHistoryUpsert {
	u.Set(certificationhistory.FieldItemBatchUUID, v)
	return u
}

// UpdateItemBatchUUID sets the "itemBatchUUID" field to the value that was provided on create.
func (u *CertificationHistoryUpsert) UpdateItemBatchUUID() *CertificationHistoryUpsert {
	u.SetExcluded(certificationhistory.FieldItemBatchUUID)
	return u
}

// SetImageUUID sets the "imageUUID" field.
func (u *CertificationHistoryUpsert) SetImageUUID(v uuid.UUID) *CertificationHistoryUpsert {
	u.Set(certificationhistory.FieldImageUUID, v)
	return u
}

// UpdateImageUUID sets the "imageUUID" field to the value that was provided on create.
func (u *CertificationHistoryUpsert) UpdateImageUUID() *CertificationHistoryUpsert {
	u.SetExcluded(certificationhistory.FieldImageUUID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CertificationHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(certificationhistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CertificationHistoryUpsertOne) UpdateNewValues() *CertificationHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(certificationhistory.FieldID)
		}
		if _, exists := u.create.mutation.HistoryTime(); exists {
			s.SetIgnore(certificationhistory.FieldHistoryTime)
		}
		if _, exists := u.create.mutation.Ref(); exists {
			s.SetIgnore(certificationhistory.FieldRef)
		}
		if _, exists := u.create.mutation.Operation(); exists {
			s.SetIgnore(certificationhistory.FieldOperation)
		}
		if _, exists := u.create.mutation.UpdatedBy(); exists {
			s.SetIgnore(certificationhistory.FieldUpdatedBy)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CertificationHistory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CertificationHistoryUpsertOne) Ignore() *CertificationHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CertificationHistoryUpsertOne) DoNothing() *CertificationHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CertificationHistoryCreate.OnConflict
// documentation for more info.
func (u *CertificationHistoryUpsertOne) Update(set func(*CertificationHistoryUpsert)) *CertificationHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CertificationHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetPrimaryAttribute sets the "primaryAttribute" field.
func (u *CertificationHistoryUpsertOne) SetPrimaryAttribute(v string) *CertificationHistoryUpsertOne {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.SetPrimaryAttribute(v)
	})
}

// UpdatePrimaryAttribute sets the "primaryAttribute" field to the value that was provided on create.
func (u *CertificationHistoryUpsertOne) UpdatePrimaryAttribute() *CertificationHistoryUpsertOne {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.UpdatePrimaryAttribute()
	})
}

// SetCompanyUUID sets the "companyUUID" field.
func (u *CertificationHistoryUpsertOne) SetCompanyUUID(v uuid.UUID) *CertificationHistoryUpsertOne {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.SetCompanyUUID(v)
	})
}

// UpdateCompanyUUID sets the "companyUUID" field to the value that was provided on create.
func (u *CertificationHistoryUpsertOne) UpdateCompanyUUID() *CertificationHistoryUpsertOne {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.UpdateCompanyUUID()
	})
}

// SetItemBatchUUID sets the "itemBatchUUID" field.
func (u *CertificationHistoryUpsertOne) SetItemBatchUUID(v uuid.UUID) *CertificationHistoryUpsertOne {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.SetItemBatchUUID(v)
	})
}

// UpdateItemBatchUUID sets the "itemBatchUUID" field to the value that was provided on create.
func (u *CertificationHistoryUpsertOne) UpdateItemBatchUUID() *CertificationHistoryUpsertOne {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.UpdateItemBatchUUID()
	})
}

// SetImageUUID sets the "imageUUID" field.
func (u *CertificationHistoryUpsertOne) SetImageUUID(v uuid.UUID) *CertificationHistoryUpsertOne {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.SetImageUUID(v)
	})
}

// UpdateImageUUID sets the "imageUUID" field to the value that was provided on create.
func (u *CertificationHistoryUpsertOne) UpdateImageUUID() *CertificationHistoryUpsertOne {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.UpdateImageUUID()
	})
}

// Exec executes the query.
func (u *CertificationHistoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CertificationHistoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CertificationHistoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CertificationHistoryUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CertificationHistoryUpsertOne.ID is not supported by MySQL driver. Use CertificationHistoryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CertificationHistoryUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CertificationHistoryCreateBulk is the builder for creating many CertificationHistory entities in bulk.
type CertificationHistoryCreateBulk struct {
	config
	builders []*CertificationHistoryCreate
	conflict []sql.ConflictOption
}

// Save creates the CertificationHistory entities in the database.
func (chcb *CertificationHistoryCreateBulk) Save(ctx context.Context) ([]*CertificationHistory, error) {
	specs := make([]*sqlgraph.CreateSpec, len(chcb.builders))
	nodes := make([]*CertificationHistory, len(chcb.builders))
	mutators := make([]Mutator, len(chcb.builders))
	for i := range chcb.builders {
		func(i int, root context.Context) {
			builder := chcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CertificationHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, chcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = chcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, chcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, chcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (chcb *CertificationHistoryCreateBulk) SaveX(ctx context.Context) []*CertificationHistory {
	v, err := chcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (chcb *CertificationHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := chcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (chcb *CertificationHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := chcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CertificationHistory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CertificationHistoryUpsert) {
//			SetHistoryTime(v+v).
//		}).
//		Exec(ctx)
func (chcb *CertificationHistoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *CertificationHistoryUpsertBulk {
	chcb.conflict = opts
	return &CertificationHistoryUpsertBulk{
		create: chcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CertificationHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (chcb *CertificationHistoryCreateBulk) OnConflictColumns(columns ...string) *CertificationHistoryUpsertBulk {
	chcb.conflict = append(chcb.conflict, sql.ConflictColumns(columns...))
	return &CertificationHistoryUpsertBulk{
		create: chcb,
	}
}

// CertificationHistoryUpsertBulk is the builder for "upsert"-ing
// a bulk of CertificationHistory nodes.
type CertificationHistoryUpsertBulk struct {
	create *CertificationHistoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CertificationHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(certificationhistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CertificationHistoryUpsertBulk) UpdateNewValues() *CertificationHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(certificationhistory.FieldID)
			}
			if _, exists := b.mutation.HistoryTime(); exists {
				s.SetIgnore(certificationhistory.FieldHistoryTime)
			}
			if _, exists := b.mutation.Ref(); exists {
				s.SetIgnore(certificationhistory.FieldRef)
			}
			if _, exists := b.mutation.Operation(); exists {
				s.SetIgnore(certificationhistory.FieldOperation)
			}
			if _, exists := b.mutation.UpdatedBy(); exists {
				s.SetIgnore(certificationhistory.FieldUpdatedBy)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CertificationHistory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CertificationHistoryUpsertBulk) Ignore() *CertificationHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CertificationHistoryUpsertBulk) DoNothing() *CertificationHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CertificationHistoryCreateBulk.OnConflict
// documentation for more info.
func (u *CertificationHistoryUpsertBulk) Update(set func(*CertificationHistoryUpsert)) *CertificationHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CertificationHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetPrimaryAttribute sets the "primaryAttribute" field.
func (u *CertificationHistoryUpsertBulk) SetPrimaryAttribute(v string) *CertificationHistoryUpsertBulk {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.SetPrimaryAttribute(v)
	})
}

// UpdatePrimaryAttribute sets the "primaryAttribute" field to the value that was provided on create.
func (u *CertificationHistoryUpsertBulk) UpdatePrimaryAttribute() *CertificationHistoryUpsertBulk {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.UpdatePrimaryAttribute()
	})
}

// SetCompanyUUID sets the "companyUUID" field.
func (u *CertificationHistoryUpsertBulk) SetCompanyUUID(v uuid.UUID) *CertificationHistoryUpsertBulk {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.SetCompanyUUID(v)
	})
}

// UpdateCompanyUUID sets the "companyUUID" field to the value that was provided on create.
func (u *CertificationHistoryUpsertBulk) UpdateCompanyUUID() *CertificationHistoryUpsertBulk {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.UpdateCompanyUUID()
	})
}

// SetItemBatchUUID sets the "itemBatchUUID" field.
func (u *CertificationHistoryUpsertBulk) SetItemBatchUUID(v uuid.UUID) *CertificationHistoryUpsertBulk {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.SetItemBatchUUID(v)
	})
}

// UpdateItemBatchUUID sets the "itemBatchUUID" field to the value that was provided on create.
func (u *CertificationHistoryUpsertBulk) UpdateItemBatchUUID() *CertificationHistoryUpsertBulk {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.UpdateItemBatchUUID()
	})
}

// SetImageUUID sets the "imageUUID" field.
func (u *CertificationHistoryUpsertBulk) SetImageUUID(v uuid.UUID) *CertificationHistoryUpsertBulk {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.SetImageUUID(v)
	})
}

// UpdateImageUUID sets the "imageUUID" field to the value that was provided on create.
func (u *CertificationHistoryUpsertBulk) UpdateImageUUID() *CertificationHistoryUpsertBulk {
	return u.Update(func(s *CertificationHistoryUpsert) {
		s.UpdateImageUUID()
	})
}

// Exec executes the query.
func (u *CertificationHistoryUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CertificationHistoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CertificationHistoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CertificationHistoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
