// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/itembatchtoitembatch"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/predicate"
)

// ItemBatchToItemBatchDelete is the builder for deleting a ItemBatchToItemBatch entity.
type ItemBatchToItemBatchDelete struct {
	config
	hooks    []Hook
	mutation *ItemBatchToItemBatchMutation
}

// Where appends a list predicates to the ItemBatchToItemBatchDelete builder.
func (ibtibd *ItemBatchToItemBatchDelete) Where(ps ...predicate.ItemBatchToItemBatch) *ItemBatchToItemBatchDelete {
	ibtibd.mutation.Where(ps...)
	return ibtibd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ibtibd *ItemBatchToItemBatchDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ibtibd.hooks) == 0 {
		affected, err = ibtibd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ItemBatchToItemBatchMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ibtibd.mutation = mutation
			affected, err = ibtibd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ibtibd.hooks) - 1; i >= 0; i-- {
			if ibtibd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ibtibd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ibtibd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ibtibd *ItemBatchToItemBatchDelete) ExecX(ctx context.Context) int {
	n, err := ibtibd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ibtibd *ItemBatchToItemBatchDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: itembatchtoitembatch.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: itembatchtoitembatch.FieldID,
			},
		},
	}
	if ps := ibtibd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ibtibd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// ItemBatchToItemBatchDeleteOne is the builder for deleting a single ItemBatchToItemBatch entity.
type ItemBatchToItemBatchDeleteOne struct {
	ibtibd *ItemBatchToItemBatchDelete
}

// Exec executes the deletion query.
func (ibtibdo *ItemBatchToItemBatchDeleteOne) Exec(ctx context.Context) error {
	n, err := ibtibdo.ibtibd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{itembatchtoitembatch.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ibtibdo *ItemBatchToItemBatchDeleteOne) ExecX(ctx context.Context) {
	ibtibdo.ibtibd.ExecX(ctx)
}
