// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/itembatch"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/predicate"
)

// ItemBatchDelete is the builder for deleting a ItemBatch entity.
type ItemBatchDelete struct {
	config
	hooks    []Hook
	mutation *ItemBatchMutation
}

// Where appends a list predicates to the ItemBatchDelete builder.
func (ibd *ItemBatchDelete) Where(ps ...predicate.ItemBatch) *ItemBatchDelete {
	ibd.mutation.Where(ps...)
	return ibd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ibd *ItemBatchDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ibd.hooks) == 0 {
		affected, err = ibd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ItemBatchMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ibd.mutation = mutation
			affected, err = ibd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ibd.hooks) - 1; i >= 0; i-- {
			if ibd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ibd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ibd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ibd *ItemBatchDelete) ExecX(ctx context.Context) int {
	n, err := ibd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ibd *ItemBatchDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: itembatch.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: itembatch.FieldID,
			},
		},
	}
	if ps := ibd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ibd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// ItemBatchDeleteOne is the builder for deleting a single ItemBatch entity.
type ItemBatchDeleteOne struct {
	ibd *ItemBatchDelete
}

// Exec executes the deletion query.
func (ibdo *ItemBatchDeleteOne) Exec(ctx context.Context) error {
	n, err := ibdo.ibd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{itembatch.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ibdo *ItemBatchDeleteOne) ExecX(ctx context.Context) {
	ibdo.ibd.ExecX(ctx)
}
