// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"

	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/attribute"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/attributetype"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/attributetypestotemplates"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/authorizationpolicy"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/certification"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/certificationtemplate"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/company"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/itembatch"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/itembatchtoitembatch"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/session"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/user"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/userstocompany"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/models"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attributeFields := models.Attribute{}.Fields()
	_ = attributeFields
	// attributeDescID is the schema descriptor for id field.
	attributeDescID := attributeFields[0].Descriptor()
	// attribute.DefaultID holds the default value on creation for the id field.
	attribute.DefaultID = attributeDescID.Default.(func() uuid.UUID)
	attributetypeFields := models.AttributeType{}.Fields()
	_ = attributetypeFields
	// attributetypeDescID is the schema descriptor for id field.
	attributetypeDescID := attributetypeFields[0].Descriptor()
	// attributetype.DefaultID holds the default value on creation for the id field.
	attributetype.DefaultID = attributetypeDescID.Default.(func() uuid.UUID)
	attributetypestotemplatesFields := models.AttributeTypesToTemplates{}.Fields()
	_ = attributetypestotemplatesFields
	// attributetypestotemplatesDescID is the schema descriptor for id field.
	attributetypestotemplatesDescID := attributetypestotemplatesFields[0].Descriptor()
	// attributetypestotemplates.DefaultID holds the default value on creation for the id field.
	attributetypestotemplates.DefaultID = attributetypestotemplatesDescID.Default.(func() uuid.UUID)
	authorizationpolicyFields := models.AuthorizationPolicy{}.Fields()
	_ = authorizationpolicyFields
	// authorizationpolicyDescPtype is the schema descriptor for Ptype field.
	authorizationpolicyDescPtype := authorizationpolicyFields[0].Descriptor()
	// authorizationpolicy.DefaultPtype holds the default value on creation for the Ptype field.
	authorizationpolicy.DefaultPtype = authorizationpolicyDescPtype.Default.(string)
	// authorizationpolicyDescV0 is the schema descriptor for V0 field.
	authorizationpolicyDescV0 := authorizationpolicyFields[1].Descriptor()
	// authorizationpolicy.DefaultV0 holds the default value on creation for the V0 field.
	authorizationpolicy.DefaultV0 = authorizationpolicyDescV0.Default.(string)
	// authorizationpolicyDescV1 is the schema descriptor for V1 field.
	authorizationpolicyDescV1 := authorizationpolicyFields[2].Descriptor()
	// authorizationpolicy.DefaultV1 holds the default value on creation for the V1 field.
	authorizationpolicy.DefaultV1 = authorizationpolicyDescV1.Default.(string)
	// authorizationpolicyDescV2 is the schema descriptor for V2 field.
	authorizationpolicyDescV2 := authorizationpolicyFields[3].Descriptor()
	// authorizationpolicy.DefaultV2 holds the default value on creation for the V2 field.
	authorizationpolicy.DefaultV2 = authorizationpolicyDescV2.Default.(string)
	// authorizationpolicyDescV3 is the schema descriptor for V3 field.
	authorizationpolicyDescV3 := authorizationpolicyFields[4].Descriptor()
	// authorizationpolicy.DefaultV3 holds the default value on creation for the V3 field.
	authorizationpolicy.DefaultV3 = authorizationpolicyDescV3.Default.(string)
	// authorizationpolicyDescV4 is the schema descriptor for V4 field.
	authorizationpolicyDescV4 := authorizationpolicyFields[5].Descriptor()
	// authorizationpolicy.DefaultV4 holds the default value on creation for the V4 field.
	authorizationpolicy.DefaultV4 = authorizationpolicyDescV4.Default.(string)
	// authorizationpolicyDescV5 is the schema descriptor for V5 field.
	authorizationpolicyDescV5 := authorizationpolicyFields[6].Descriptor()
	// authorizationpolicy.DefaultV5 holds the default value on creation for the V5 field.
	authorizationpolicy.DefaultV5 = authorizationpolicyDescV5.Default.(string)
	certificationFields := models.Certification{}.Fields()
	_ = certificationFields
	// certificationDescID is the schema descriptor for id field.
	certificationDescID := certificationFields[0].Descriptor()
	// certification.DefaultID holds the default value on creation for the id field.
	certification.DefaultID = certificationDescID.Default.(func() uuid.UUID)
	certificationtemplateFields := models.CertificationTemplate{}.Fields()
	_ = certificationtemplateFields
	// certificationtemplateDescID is the schema descriptor for id field.
	certificationtemplateDescID := certificationtemplateFields[0].Descriptor()
	// certificationtemplate.DefaultID holds the default value on creation for the id field.
	certificationtemplate.DefaultID = certificationtemplateDescID.Default.(func() uuid.UUID)
	companyFields := models.Company{}.Fields()
	_ = companyFields
	// companyDescID is the schema descriptor for id field.
	companyDescID := companyFields[0].Descriptor()
	// company.DefaultID holds the default value on creation for the id field.
	company.DefaultID = companyDescID.Default.(func() uuid.UUID)
	itembatchFields := models.ItemBatch{}.Fields()
	_ = itembatchFields
	// itembatchDescID is the schema descriptor for id field.
	itembatchDescID := itembatchFields[0].Descriptor()
	// itembatch.DefaultID holds the default value on creation for the id field.
	itembatch.DefaultID = itembatchDescID.Default.(func() uuid.UUID)
	itembatchtoitembatchFields := models.ItemBatchToItemBatch{}.Fields()
	_ = itembatchtoitembatchFields
	// itembatchtoitembatchDescID is the schema descriptor for id field.
	itembatchtoitembatchDescID := itembatchtoitembatchFields[0].Descriptor()
	// itembatchtoitembatch.DefaultID holds the default value on creation for the id field.
	itembatchtoitembatch.DefaultID = itembatchtoitembatchDescID.Default.(func() uuid.UUID)
	sessionFields := models.Session{}.Fields()
	_ = sessionFields
	// sessionDescData is the schema descriptor for data field.
	sessionDescData := sessionFields[1].Descriptor()
	// session.DataValidator is a validator for the "data" field. It is called by the builders before save.
	session.DataValidator = sessionDescData.Validators[0].(func([]byte) error)
	userFields := models.User{}.Fields()
	_ = userFields
	// userDescUUID is the schema descriptor for UUID field.
	userDescUUID := userFields[1].Descriptor()
	// user.DefaultUUID holds the default value on creation for the UUID field.
	user.DefaultUUID = userDescUUID.Default.(func() uuid.UUID)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[3].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(time.Time)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[9].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int) error)
	userstocompanyFields := models.UsersToCompany{}.Fields()
	_ = userstocompanyFields
	// userstocompanyDescID is the schema descriptor for id field.
	userstocompanyDescID := userstocompanyFields[0].Descriptor()
	// userstocompany.DefaultID holds the default value on creation for the id field.
	userstocompany.DefaultID = userstocompanyDescID.Default.(func() uuid.UUID)
}
