// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/predicate"
	"git.las.iastate.edu/SeniorDesignComS/2023spr/online-certificate-repo/backend/pkg/database/ent/userhistory"
)

// UserHistoryUpdate is the builder for updating UserHistory entities.
type UserHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *UserHistoryMutation
}

// Where appends a list predicates to the UserHistoryUpdate builder.
func (uhu *UserHistoryUpdate) Where(ps ...predicate.UserHistory) *UserHistoryUpdate {
	uhu.mutation.Where(ps...)
	return uhu
}

// SetEmail sets the "email" field.
func (uhu *UserHistoryUpdate) SetEmail(s string) *UserHistoryUpdate {
	uhu.mutation.SetEmail(s)
	return uhu
}

// SetUpdatedAt sets the "updated_at" field.
func (uhu *UserHistoryUpdate) SetUpdatedAt(t time.Time) *UserHistoryUpdate {
	uhu.mutation.SetUpdatedAt(t)
	return uhu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uhu *UserHistoryUpdate) SetNillableUpdatedAt(t *time.Time) *UserHistoryUpdate {
	if t != nil {
		uhu.SetUpdatedAt(*t)
	}
	return uhu
}

// SetPasswordHash sets the "password_hash" field.
func (uhu *UserHistoryUpdate) SetPasswordHash(s string) *UserHistoryUpdate {
	uhu.mutation.SetPasswordHash(s)
	return uhu
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (uhu *UserHistoryUpdate) SetNillablePasswordHash(s *string) *UserHistoryUpdate {
	if s != nil {
		uhu.SetPasswordHash(*s)
	}
	return uhu
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (uhu *UserHistoryUpdate) ClearPasswordHash() *UserHistoryUpdate {
	uhu.mutation.ClearPasswordHash()
	return uhu
}

// SetAttemptCount sets the "attempt_count" field.
func (uhu *UserHistoryUpdate) SetAttemptCount(i int) *UserHistoryUpdate {
	uhu.mutation.ResetAttemptCount()
	uhu.mutation.SetAttemptCount(i)
	return uhu
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (uhu *UserHistoryUpdate) SetNillableAttemptCount(i *int) *UserHistoryUpdate {
	if i != nil {
		uhu.SetAttemptCount(*i)
	}
	return uhu
}

// AddAttemptCount adds i to the "attempt_count" field.
func (uhu *UserHistoryUpdate) AddAttemptCount(i int) *UserHistoryUpdate {
	uhu.mutation.AddAttemptCount(i)
	return uhu
}

// ClearAttemptCount clears the value of the "attempt_count" field.
func (uhu *UserHistoryUpdate) ClearAttemptCount() *UserHistoryUpdate {
	uhu.mutation.ClearAttemptCount()
	return uhu
}

// SetLastAttempt sets the "last_attempt" field.
func (uhu *UserHistoryUpdate) SetLastAttempt(t time.Time) *UserHistoryUpdate {
	uhu.mutation.SetLastAttempt(t)
	return uhu
}

// SetNillableLastAttempt sets the "last_attempt" field if the given value is not nil.
func (uhu *UserHistoryUpdate) SetNillableLastAttempt(t *time.Time) *UserHistoryUpdate {
	if t != nil {
		uhu.SetLastAttempt(*t)
	}
	return uhu
}

// ClearLastAttempt clears the value of the "last_attempt" field.
func (uhu *UserHistoryUpdate) ClearLastAttempt() *UserHistoryUpdate {
	uhu.mutation.ClearLastAttempt()
	return uhu
}

// SetLocked sets the "locked" field.
func (uhu *UserHistoryUpdate) SetLocked(t time.Time) *UserHistoryUpdate {
	uhu.mutation.SetLocked(t)
	return uhu
}

// SetNillableLocked sets the "locked" field if the given value is not nil.
func (uhu *UserHistoryUpdate) SetNillableLocked(t *time.Time) *UserHistoryUpdate {
	if t != nil {
		uhu.SetLocked(*t)
	}
	return uhu
}

// ClearLocked clears the value of the "locked" field.
func (uhu *UserHistoryUpdate) ClearLocked() *UserHistoryUpdate {
	uhu.mutation.ClearLocked()
	return uhu
}

// SetRole sets the "role" field.
func (uhu *UserHistoryUpdate) SetRole(s string) *UserHistoryUpdate {
	uhu.mutation.SetRole(s)
	return uhu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (uhu *UserHistoryUpdate) SetNillableRole(s *string) *UserHistoryUpdate {
	if s != nil {
		uhu.SetRole(*s)
	}
	return uhu
}

// Mutation returns the UserHistoryMutation object of the builder.
func (uhu *UserHistoryUpdate) Mutation() *UserHistoryMutation {
	return uhu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uhu *UserHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, UserHistoryMutation](ctx, uhu.sqlSave, uhu.mutation, uhu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uhu *UserHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := uhu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uhu *UserHistoryUpdate) Exec(ctx context.Context) error {
	_, err := uhu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uhu *UserHistoryUpdate) ExecX(ctx context.Context) {
	if err := uhu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uhu *UserHistoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userhistory.Table, userhistory.Columns, sqlgraph.NewFieldSpec(userhistory.FieldID, field.TypeUUID))
	if ps := uhu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if uhu.mutation.RefCleared() {
		_spec.ClearField(userhistory.FieldRef, field.TypeUUID)
	}
	if uhu.mutation.UpdatedByCleared() {
		_spec.ClearField(userhistory.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := uhu.mutation.Email(); ok {
		_spec.SetField(userhistory.FieldEmail, field.TypeString, value)
	}
	if value, ok := uhu.mutation.UpdatedAt(); ok {
		_spec.SetField(userhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uhu.mutation.PasswordHash(); ok {
		_spec.SetField(userhistory.FieldPasswordHash, field.TypeString, value)
	}
	if uhu.mutation.PasswordHashCleared() {
		_spec.ClearField(userhistory.FieldPasswordHash, field.TypeString)
	}
	if value, ok := uhu.mutation.AttemptCount(); ok {
		_spec.SetField(userhistory.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := uhu.mutation.AddedAttemptCount(); ok {
		_spec.AddField(userhistory.FieldAttemptCount, field.TypeInt, value)
	}
	if uhu.mutation.AttemptCountCleared() {
		_spec.ClearField(userhistory.FieldAttemptCount, field.TypeInt)
	}
	if value, ok := uhu.mutation.LastAttempt(); ok {
		_spec.SetField(userhistory.FieldLastAttempt, field.TypeTime, value)
	}
	if uhu.mutation.LastAttemptCleared() {
		_spec.ClearField(userhistory.FieldLastAttempt, field.TypeTime)
	}
	if value, ok := uhu.mutation.Locked(); ok {
		_spec.SetField(userhistory.FieldLocked, field.TypeTime, value)
	}
	if uhu.mutation.LockedCleared() {
		_spec.ClearField(userhistory.FieldLocked, field.TypeTime)
	}
	if value, ok := uhu.mutation.Role(); ok {
		_spec.SetField(userhistory.FieldRole, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uhu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uhu.mutation.done = true
	return n, nil
}

// UserHistoryUpdateOne is the builder for updating a single UserHistory entity.
type UserHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserHistoryMutation
}

// SetEmail sets the "email" field.
func (uhuo *UserHistoryUpdateOne) SetEmail(s string) *UserHistoryUpdateOne {
	uhuo.mutation.SetEmail(s)
	return uhuo
}

// SetUpdatedAt sets the "updated_at" field.
func (uhuo *UserHistoryUpdateOne) SetUpdatedAt(t time.Time) *UserHistoryUpdateOne {
	uhuo.mutation.SetUpdatedAt(t)
	return uhuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uhuo *UserHistoryUpdateOne) SetNillableUpdatedAt(t *time.Time) *UserHistoryUpdateOne {
	if t != nil {
		uhuo.SetUpdatedAt(*t)
	}
	return uhuo
}

// SetPasswordHash sets the "password_hash" field.
func (uhuo *UserHistoryUpdateOne) SetPasswordHash(s string) *UserHistoryUpdateOne {
	uhuo.mutation.SetPasswordHash(s)
	return uhuo
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (uhuo *UserHistoryUpdateOne) SetNillablePasswordHash(s *string) *UserHistoryUpdateOne {
	if s != nil {
		uhuo.SetPasswordHash(*s)
	}
	return uhuo
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (uhuo *UserHistoryUpdateOne) ClearPasswordHash() *UserHistoryUpdateOne {
	uhuo.mutation.ClearPasswordHash()
	return uhuo
}

// SetAttemptCount sets the "attempt_count" field.
func (uhuo *UserHistoryUpdateOne) SetAttemptCount(i int) *UserHistoryUpdateOne {
	uhuo.mutation.ResetAttemptCount()
	uhuo.mutation.SetAttemptCount(i)
	return uhuo
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (uhuo *UserHistoryUpdateOne) SetNillableAttemptCount(i *int) *UserHistoryUpdateOne {
	if i != nil {
		uhuo.SetAttemptCount(*i)
	}
	return uhuo
}

// AddAttemptCount adds i to the "attempt_count" field.
func (uhuo *UserHistoryUpdateOne) AddAttemptCount(i int) *UserHistoryUpdateOne {
	uhuo.mutation.AddAttemptCount(i)
	return uhuo
}

// ClearAttemptCount clears the value of the "attempt_count" field.
func (uhuo *UserHistoryUpdateOne) ClearAttemptCount() *UserHistoryUpdateOne {
	uhuo.mutation.ClearAttemptCount()
	return uhuo
}

// SetLastAttempt sets the "last_attempt" field.
func (uhuo *UserHistoryUpdateOne) SetLastAttempt(t time.Time) *UserHistoryUpdateOne {
	uhuo.mutation.SetLastAttempt(t)
	return uhuo
}

// SetNillableLastAttempt sets the "last_attempt" field if the given value is not nil.
func (uhuo *UserHistoryUpdateOne) SetNillableLastAttempt(t *time.Time) *UserHistoryUpdateOne {
	if t != nil {
		uhuo.SetLastAttempt(*t)
	}
	return uhuo
}

// ClearLastAttempt clears the value of the "last_attempt" field.
func (uhuo *UserHistoryUpdateOne) ClearLastAttempt() *UserHistoryUpdateOne {
	uhuo.mutation.ClearLastAttempt()
	return uhuo
}

// SetLocked sets the "locked" field.
func (uhuo *UserHistoryUpdateOne) SetLocked(t time.Time) *UserHistoryUpdateOne {
	uhuo.mutation.SetLocked(t)
	return uhuo
}

// SetNillableLocked sets the "locked" field if the given value is not nil.
func (uhuo *UserHistoryUpdateOne) SetNillableLocked(t *time.Time) *UserHistoryUpdateOne {
	if t != nil {
		uhuo.SetLocked(*t)
	}
	return uhuo
}

// ClearLocked clears the value of the "locked" field.
func (uhuo *UserHistoryUpdateOne) ClearLocked() *UserHistoryUpdateOne {
	uhuo.mutation.ClearLocked()
	return uhuo
}

// SetRole sets the "role" field.
func (uhuo *UserHistoryUpdateOne) SetRole(s string) *UserHistoryUpdateOne {
	uhuo.mutation.SetRole(s)
	return uhuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (uhuo *UserHistoryUpdateOne) SetNillableRole(s *string) *UserHistoryUpdateOne {
	if s != nil {
		uhuo.SetRole(*s)
	}
	return uhuo
}

// Mutation returns the UserHistoryMutation object of the builder.
func (uhuo *UserHistoryUpdateOne) Mutation() *UserHistoryMutation {
	return uhuo.mutation
}

// Where appends a list predicates to the UserHistoryUpdate builder.
func (uhuo *UserHistoryUpdateOne) Where(ps ...predicate.UserHistory) *UserHistoryUpdateOne {
	uhuo.mutation.Where(ps...)
	return uhuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uhuo *UserHistoryUpdateOne) Select(field string, fields ...string) *UserHistoryUpdateOne {
	uhuo.fields = append([]string{field}, fields...)
	return uhuo
}

// Save executes the query and returns the updated UserHistory entity.
func (uhuo *UserHistoryUpdateOne) Save(ctx context.Context) (*UserHistory, error) {
	return withHooks[*UserHistory, UserHistoryMutation](ctx, uhuo.sqlSave, uhuo.mutation, uhuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uhuo *UserHistoryUpdateOne) SaveX(ctx context.Context) *UserHistory {
	node, err := uhuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uhuo *UserHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := uhuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uhuo *UserHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := uhuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uhuo *UserHistoryUpdateOne) sqlSave(ctx context.Context) (_node *UserHistory, err error) {
	_spec := sqlgraph.NewUpdateSpec(userhistory.Table, userhistory.Columns, sqlgraph.NewFieldSpec(userhistory.FieldID, field.TypeUUID))
	id, ok := uhuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uhuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userhistory.FieldID)
		for _, f := range fields {
			if !userhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uhuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if uhuo.mutation.RefCleared() {
		_spec.ClearField(userhistory.FieldRef, field.TypeUUID)
	}
	if uhuo.mutation.UpdatedByCleared() {
		_spec.ClearField(userhistory.FieldUpdatedBy, field.TypeString)
	}
	if value, ok := uhuo.mutation.Email(); ok {
		_spec.SetField(userhistory.FieldEmail, field.TypeString, value)
	}
	if value, ok := uhuo.mutation.UpdatedAt(); ok {
		_spec.SetField(userhistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := uhuo.mutation.PasswordHash(); ok {
		_spec.SetField(userhistory.FieldPasswordHash, field.TypeString, value)
	}
	if uhuo.mutation.PasswordHashCleared() {
		_spec.ClearField(userhistory.FieldPasswordHash, field.TypeString)
	}
	if value, ok := uhuo.mutation.AttemptCount(); ok {
		_spec.SetField(userhistory.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := uhuo.mutation.AddedAttemptCount(); ok {
		_spec.AddField(userhistory.FieldAttemptCount, field.TypeInt, value)
	}
	if uhuo.mutation.AttemptCountCleared() {
		_spec.ClearField(userhistory.FieldAttemptCount, field.TypeInt)
	}
	if value, ok := uhuo.mutation.LastAttempt(); ok {
		_spec.SetField(userhistory.FieldLastAttempt, field.TypeTime, value)
	}
	if uhuo.mutation.LastAttemptCleared() {
		_spec.ClearField(userhistory.FieldLastAttempt, field.TypeTime)
	}
	if value, ok := uhuo.mutation.Locked(); ok {
		_spec.SetField(userhistory.FieldLocked, field.TypeTime, value)
	}
	if uhuo.mutation.LockedCleared() {
		_spec.ClearField(userhistory.FieldLocked, field.TypeTime)
	}
	if value, ok := uhuo.mutation.Role(); ok {
		_spec.SetField(userhistory.FieldRole, field.TypeString, value)
	}
	_node = &UserHistory{config: uhuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uhuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uhuo.mutation.done = true
	return _node, nil
}
