// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "confirm_selector", Type: field.TypeString, Nullable: true},
		{Name: "confirm_verifier", Type: field.TypeString, Nullable: true},
		{Name: "confirmed", Type: field.TypeBool, Nullable: true},
		{Name: "attempt_count", Type: field.TypeInt, Nullable: true},
		{Name: "last_attempt", Type: field.TypeTime, Nullable: true},
		{Name: "locked", Type: field.TypeTime, Nullable: true},
		{Name: "recover_selector", Type: field.TypeString, Nullable: true},
		{Name: "recover_verifier", Type: field.TypeString, Nullable: true},
		{Name: "recover_token_expiry", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
