// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttributesColumns holds the columns for the "attributes" table.
	AttributesColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "cert_uuid", Type: field.TypeUUID},
		{Name: "attribute_type_uuid", Type: field.TypeUUID},
	}
	// AttributesTable holds the schema information for the "attributes" table.
	AttributesTable = &schema.Table{
		Name:       "attributes",
		Columns:    AttributesColumns,
		PrimaryKey: []*schema.Column{AttributesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attributes_certifications_certification",
				Columns:    []*schema.Column{AttributesColumns[3]},
				RefColumns: []*schema.Column{CertificationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "attributes_attribute_types_attributeType",
				Columns:    []*schema.Column{AttributesColumns[4]},
				RefColumns: []*schema.Column{AttributeTypesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AttributeHistoryColumns holds the columns for the "attribute_history" table.
	AttributeHistoryColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "history_time", Type: field.TypeTime},
		{Name: "ref", Type: field.TypeUUID, Nullable: true},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"INSERT", "UPDATE", "DELETE"}},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "cert_uuid", Type: field.TypeUUID},
		{Name: "attribute_type_uuid", Type: field.TypeUUID},
	}
	// AttributeHistoryTable holds the schema information for the "attribute_history" table.
	AttributeHistoryTable = &schema.Table{
		Name:       "attribute_history",
		Columns:    AttributeHistoryColumns,
		PrimaryKey: []*schema.Column{AttributeHistoryColumns[0]},
	}
	// AttributeTypesColumns holds the columns for the "attribute_types" table.
	AttributeTypesColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString},
		{Name: "company_uuid", Type: field.TypeUUID},
	}
	// AttributeTypesTable holds the schema information for the "attribute_types" table.
	AttributeTypesTable = &schema.Table{
		Name:       "attribute_types",
		Columns:    AttributeTypesColumns,
		PrimaryKey: []*schema.Column{AttributeTypesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attribute_types_companies_company",
				Columns:    []*schema.Column{AttributeTypesColumns[2]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AttributeTypeHistoryColumns holds the columns for the "attribute_type_history" table.
	AttributeTypeHistoryColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "history_time", Type: field.TypeTime},
		{Name: "ref", Type: field.TypeUUID, Nullable: true},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"INSERT", "UPDATE", "DELETE"}},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "key", Type: field.TypeString},
		{Name: "company_uuid", Type: field.TypeUUID},
	}
	// AttributeTypeHistoryTable holds the schema information for the "attribute_type_history" table.
	AttributeTypeHistoryTable = &schema.Table{
		Name:       "attribute_type_history",
		Columns:    AttributeTypeHistoryColumns,
		PrimaryKey: []*schema.Column{AttributeTypeHistoryColumns[0]},
	}
	// AuthorizationPoliciesColumns holds the columns for the "authorization_policies" table.
	AuthorizationPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ptype", Type: field.TypeString, Default: ""},
		{Name: "v0", Type: field.TypeString, Default: ""},
		{Name: "v1", Type: field.TypeString, Default: ""},
		{Name: "v2", Type: field.TypeString, Default: ""},
		{Name: "v3", Type: field.TypeString, Default: ""},
		{Name: "v4", Type: field.TypeString, Default: ""},
		{Name: "v5", Type: field.TypeString, Default: ""},
	}
	// AuthorizationPoliciesTable holds the schema information for the "authorization_policies" table.
	AuthorizationPoliciesTable = &schema.Table{
		Name:       "authorization_policies",
		Columns:    AuthorizationPoliciesColumns,
		PrimaryKey: []*schema.Column{AuthorizationPoliciesColumns[0]},
	}
	// CertificationsColumns holds the columns for the "certifications" table.
	CertificationsColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "primary_attribute", Type: field.TypeString},
		{Name: "image_uuid", Type: field.TypeUUID},
		{Name: "company_uuid", Type: field.TypeUUID},
		{Name: "item_batch_uuid", Type: field.TypeUUID},
	}
	// CertificationsTable holds the schema information for the "certifications" table.
	CertificationsTable = &schema.Table{
		Name:       "certifications",
		Columns:    CertificationsColumns,
		PrimaryKey: []*schema.Column{CertificationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "certifications_companies_company",
				Columns:    []*schema.Column{CertificationsColumns[3]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "certifications_item_batches_itemBatch",
				Columns:    []*schema.Column{CertificationsColumns[4]},
				RefColumns: []*schema.Column{ItemBatchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CertificationHistoryColumns holds the columns for the "certification_history" table.
	CertificationHistoryColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "history_time", Type: field.TypeTime},
		{Name: "ref", Type: field.TypeUUID, Nullable: true},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"INSERT", "UPDATE", "DELETE"}},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "primary_attribute", Type: field.TypeString},
		{Name: "company_uuid", Type: field.TypeUUID},
		{Name: "item_batch_uuid", Type: field.TypeUUID},
		{Name: "image_uuid", Type: field.TypeUUID},
	}
	// CertificationHistoryTable holds the schema information for the "certification_history" table.
	CertificationHistoryTable = &schema.Table{
		Name:       "certification_history",
		Columns:    CertificationHistoryColumns,
		PrimaryKey: []*schema.Column{CertificationHistoryColumns[0]},
	}
	// CertificationTemplatesColumns holds the columns for the "certification_templates" table.
	CertificationTemplatesColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "description", Type: field.TypeString},
		{Name: "company_uuid", Type: field.TypeUUID},
	}
	// CertificationTemplatesTable holds the schema information for the "certification_templates" table.
	CertificationTemplatesTable = &schema.Table{
		Name:       "certification_templates",
		Columns:    CertificationTemplatesColumns,
		PrimaryKey: []*schema.Column{CertificationTemplatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "certification_templates_companies_company",
				Columns:    []*schema.Column{CertificationTemplatesColumns[2]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CertificationTemplateHistoryColumns holds the columns for the "certification_template_history" table.
	CertificationTemplateHistoryColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "history_time", Type: field.TypeTime},
		{Name: "ref", Type: field.TypeUUID, Nullable: true},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"INSERT", "UPDATE", "DELETE"}},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString},
		{Name: "company_uuid", Type: field.TypeUUID},
	}
	// CertificationTemplateHistoryTable holds the schema information for the "certification_template_history" table.
	CertificationTemplateHistoryTable = &schema.Table{
		Name:       "certification_template_history",
		Columns:    CertificationTemplateHistoryColumns,
		PrimaryKey: []*schema.Column{CertificationTemplateHistoryColumns[0]},
	}
	// CompaniesColumns holds the columns for the "companies" table.
	CompaniesColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// CompaniesTable holds the schema information for the "companies" table.
	CompaniesTable = &schema.Table{
		Name:       "companies",
		Columns:    CompaniesColumns,
		PrimaryKey: []*schema.Column{CompaniesColumns[0]},
	}
	// CompanyHistoryColumns holds the columns for the "company_history" table.
	CompanyHistoryColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID, Unique: true},
		{Name: "history_time", Type: field.TypeTime},
		{Name: "ref", Type: field.TypeUUID, Nullable: true},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"INSERT", "UPDATE", "DELETE"}},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString},
	}
	// CompanyHistoryTable holds the schema information for the "company_history" table.
	CompanyHistoryTable = &schema.Table{
		Name:       "company_history",
		Columns:    CompanyHistoryColumns,
		PrimaryKey: []*schema.Column{CompanyHistoryColumns[0]},
	}
	// ItemBatchesColumns holds the columns for the "item_batches" table.
	ItemBatchesColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "item_number", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "company_uuid", Type: field.TypeUUID},
	}
	// ItemBatchesTable holds the schema information for the "item_batches" table.
	ItemBatchesTable = &schema.Table{
		Name:       "item_batches",
		Columns:    ItemBatchesColumns,
		PrimaryKey: []*schema.Column{ItemBatchesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "item_batches_companies_company",
				Columns:    []*schema.Column{ItemBatchesColumns[3]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ItemBatchHistoryColumns holds the columns for the "item_batch_history" table.
	ItemBatchHistoryColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "history_time", Type: field.TypeTime},
		{Name: "ref", Type: field.TypeUUID, Nullable: true},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"INSERT", "UPDATE", "DELETE"}},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "item_number", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "company_uuid", Type: field.TypeUUID},
	}
	// ItemBatchHistoryTable holds the schema information for the "item_batch_history" table.
	ItemBatchHistoryTable = &schema.Table{
		Name:       "item_batch_history",
		Columns:    ItemBatchHistoryColumns,
		PrimaryKey: []*schema.Column{ItemBatchHistoryColumns[0]},
	}
	// ItemBatchToItemBatchesColumns holds the columns for the "item_batch_to_item_batches" table.
	ItemBatchToItemBatchesColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "parent_uuid", Type: field.TypeUUID},
		{Name: "child_uuid", Type: field.TypeUUID},
	}
	// ItemBatchToItemBatchesTable holds the schema information for the "item_batch_to_item_batches" table.
	ItemBatchToItemBatchesTable = &schema.Table{
		Name:       "item_batch_to_item_batches",
		Columns:    ItemBatchToItemBatchesColumns,
		PrimaryKey: []*schema.Column{ItemBatchToItemBatchesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "item_batch_to_item_batches_item_batches_parent",
				Columns:    []*schema.Column{ItemBatchToItemBatchesColumns[1]},
				RefColumns: []*schema.Column{ItemBatchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "item_batch_to_item_batches_item_batches_child",
				Columns:    []*schema.Column{ItemBatchToItemBatchesColumns[2]},
				RefColumns: []*schema.Column{ItemBatchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ItemBatchToItemBatchHistoryColumns holds the columns for the "item_batch_to_item_batch_history" table.
	ItemBatchToItemBatchHistoryColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "history_time", Type: field.TypeTime},
		{Name: "ref", Type: field.TypeUUID, Nullable: true},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"INSERT", "UPDATE", "DELETE"}},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "child_uuid", Type: field.TypeUUID},
		{Name: "parent_uuid", Type: field.TypeUUID},
	}
	// ItemBatchToItemBatchHistoryTable holds the schema information for the "item_batch_to_item_batch_history" table.
	ItemBatchToItemBatchHistoryTable = &schema.Table{
		Name:       "item_batch_to_item_batch_history",
		Columns:    ItemBatchToItemBatchHistoryColumns,
		PrimaryKey: []*schema.Column{ItemBatchToItemBatchHistoryColumns[0]},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "data", Type: field.TypeBytes},
		{Name: "expiry", Type: field.TypeTime},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "attempt_count", Type: field.TypeInt, Nullable: true},
		{Name: "last_attempt", Type: field.TypeTime, Nullable: true},
		{Name: "locked", Type: field.TypeTime, Nullable: true},
		{Name: "role", Type: field.TypeString, Default: "user"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserHistoryColumns holds the columns for the "user_history" table.
	UserHistoryColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID},
		{Name: "history_time", Type: field.TypeTime},
		{Name: "ref", Type: field.TypeUUID, Nullable: true},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"INSERT", "UPDATE", "DELETE"}},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "attempt_count", Type: field.TypeInt, Nullable: true},
		{Name: "last_attempt", Type: field.TypeTime, Nullable: true},
		{Name: "locked", Type: field.TypeTime, Nullable: true},
		{Name: "role", Type: field.TypeString, Default: "user"},
	}
	// UserHistoryTable holds the schema information for the "user_history" table.
	UserHistoryTable = &schema.Table{
		Name:       "user_history",
		Columns:    UserHistoryColumns,
		PrimaryKey: []*schema.Column{UserHistoryColumns[0]},
	}
	// UsersToCompaniesColumns holds the columns for the "users_to_companies" table.
	UsersToCompaniesColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID, Unique: true},
		{Name: "role_type", Type: field.TypeString},
		{Name: "approved", Type: field.TypeBool},
		{Name: "user_uuid", Type: field.TypeUUID},
		{Name: "company_uuid", Type: field.TypeUUID},
	}
	// UsersToCompaniesTable holds the schema information for the "users_to_companies" table.
	UsersToCompaniesTable = &schema.Table{
		Name:       "users_to_companies",
		Columns:    UsersToCompaniesColumns,
		PrimaryKey: []*schema.Column{UsersToCompaniesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_to_companies_users_user",
				Columns:    []*schema.Column{UsersToCompaniesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "users_to_companies_companies_company",
				Columns:    []*schema.Column{UsersToCompaniesColumns[4]},
				RefColumns: []*schema.Column{CompaniesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersToCompanyHistoryColumns holds the columns for the "users_to_company_history" table.
	UsersToCompanyHistoryColumns = []*schema.Column{
		{Name: "UUID", Type: field.TypeUUID, Unique: true},
		{Name: "history_time", Type: field.TypeTime},
		{Name: "ref", Type: field.TypeUUID, Nullable: true},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"INSERT", "UPDATE", "DELETE"}},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "company_uuid", Type: field.TypeUUID},
		{Name: "user_uuid", Type: field.TypeUUID},
		{Name: "role_type", Type: field.TypeString},
		{Name: "approved", Type: field.TypeBool},
	}
	// UsersToCompanyHistoryTable holds the schema information for the "users_to_company_history" table.
	UsersToCompanyHistoryTable = &schema.Table{
		Name:       "users_to_company_history",
		Columns:    UsersToCompanyHistoryColumns,
		PrimaryKey: []*schema.Column{UsersToCompanyHistoryColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttributesTable,
		AttributeHistoryTable,
		AttributeTypesTable,
		AttributeTypeHistoryTable,
		AuthorizationPoliciesTable,
		CertificationsTable,
		CertificationHistoryTable,
		CertificationTemplatesTable,
		CertificationTemplateHistoryTable,
		CompaniesTable,
		CompanyHistoryTable,
		ItemBatchesTable,
		ItemBatchHistoryTable,
		ItemBatchToItemBatchesTable,
		ItemBatchToItemBatchHistoryTable,
		SessionsTable,
		UsersTable,
		UserHistoryTable,
		UsersToCompaniesTable,
		UsersToCompanyHistoryTable,
	}
)

func init() {
	AttributesTable.ForeignKeys[0].RefTable = CertificationsTable
	AttributesTable.ForeignKeys[1].RefTable = AttributeTypesTable
	AttributeHistoryTable.Annotation = &entsql.Annotation{
		Table: "attribute_history",
	}
	AttributeTypesTable.ForeignKeys[0].RefTable = CompaniesTable
	AttributeTypeHistoryTable.Annotation = &entsql.Annotation{
		Table: "attribute_type_history",
	}
	CertificationsTable.ForeignKeys[0].RefTable = CompaniesTable
	CertificationsTable.ForeignKeys[1].RefTable = ItemBatchesTable
	CertificationHistoryTable.Annotation = &entsql.Annotation{
		Table: "certification_history",
	}
	CertificationTemplatesTable.ForeignKeys[0].RefTable = CompaniesTable
	CertificationTemplateHistoryTable.Annotation = &entsql.Annotation{
		Table: "certification_template_history",
	}
	CompanyHistoryTable.Annotation = &entsql.Annotation{
		Table: "company_history",
	}
	ItemBatchesTable.ForeignKeys[0].RefTable = CompaniesTable
	ItemBatchHistoryTable.Annotation = &entsql.Annotation{
		Table: "item_batch_history",
	}
	ItemBatchToItemBatchesTable.ForeignKeys[0].RefTable = ItemBatchesTable
	ItemBatchToItemBatchesTable.ForeignKeys[1].RefTable = ItemBatchesTable
	ItemBatchToItemBatchHistoryTable.Annotation = &entsql.Annotation{
		Table: "item_batch_to_item_batch_history",
	}
	UserHistoryTable.Annotation = &entsql.Annotation{
		Table: "user_history",
	}
	UsersToCompaniesTable.ForeignKeys[0].RefTable = UsersTable
	UsersToCompaniesTable.ForeignKeys[1].RefTable = CompaniesTable
	UsersToCompanyHistoryTable.Annotation = &entsql.Annotation{
		Table: "users_to_company_history",
	}
}
